import { NodeType } from "@/types";
import {
  MessageSquare, Mail, AtSign, UserPlus, UserMinus, SmilePlus, Terminal, Search, Clock,
  PlusCircle, Shield, Play, Send, Reply, Trash2, Pin, Hash, Pencil,
  ShieldPlus, ShieldMinus, UserX, Ban, VolumeX, Tag, FileText, Timer,
  Database, Shuffle, GitBranch, ScrollText, Globe, Braces, Calculator,
  Type, Repeat, MousePointerClick, Tally3,
  Loader2, MessageCircle, Regex, ListTree, IterationCw, List, Hourglass, Webhook, LayoutDashboard, BarChart3,
} from "lucide-react";

export interface VarEmit {
  name: string;
  description: string;
}

export interface NodeDef {
  type: NodeType;
  label: string;
  category: "trigger" | "action" | "logic" | "data";
  color: string;       // tailwind bg class for the node header
  borderColor: string;
  icon: React.ElementType;
  inputs: string[];     // port names
  outputs: string[];
  fields: FieldDef[];   // config fields for this node
  emits: VarEmit[];     // variables this node provides to downstream nodes
}

export interface FieldDef {
  key: string;
  label: string;
  type: "text" | "textarea" | "number" | "select";
  placeholder?: string;
  options?: { value: string; label: string }[];
  defaultValue?: string;
}

export const NODE_DEFS: NodeDef[] = [
  // ===== TRIGGERS =====
  { type: "trigger_on_message", label: "On Message", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: MessageSquare, inputs: [], outputs: ["out"], fields: [{ key: "channel_id", label: "Channel (empty = all)", type: "text", placeholder: "Channel ID" }], emits: [{ name: "content", description: "Message text" }, { name: "user_id", description: "Sender's user ID" }, { name: "username", description: "Sender's username" }, { name: "channel_id", description: "Channel ID" }, { name: "server_id", description: "Server ID" }, { name: "message_id", description: "Message ID" }, { name: "timestamp", description: "When sent" }] },
  { type: "trigger_on_dm", label: "On DM", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: Mail, inputs: [], outputs: ["out"], fields: [], emits: [{ name: "content", description: "DM text" }, { name: "user_id", description: "Sender's user ID" }, { name: "username", description: "Sender's username" }, { name: "message_id", description: "Message ID" }, { name: "timestamp", description: "When sent" }] },
  { type: "trigger_on_mention", label: "On Mention", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: AtSign, inputs: [], outputs: ["out"], fields: [], emits: [{ name: "content", description: "Message text" }, { name: "user_id", description: "Mentioner's user ID" }, { name: "username", description: "Mentioner's username" }, { name: "channel_id", description: "Channel ID" }, { name: "server_id", description: "Server ID" }, { name: "message_id", description: "Message ID" }, { name: "timestamp", description: "When sent" }] },
  { type: "trigger_on_join", label: "On User Join", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: UserPlus, inputs: [], outputs: ["out"], fields: [], emits: [{ name: "user_id", description: "Joining user's ID" }, { name: "username", description: "Joining user's name" }, { name: "server_id", description: "Server joined" }, { name: "timestamp", description: "When joined" }] },
  { type: "trigger_on_leave", label: "On User Leave", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: UserMinus, inputs: [], outputs: ["out"], fields: [], emits: [{ name: "user_id", description: "Leaving user's ID" }, { name: "username", description: "Leaving user's name" }, { name: "server_id", description: "Server left" }, { name: "timestamp", description: "When left" }] },
  { type: "trigger_on_reaction", label: "On Reaction", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: SmilePlus, inputs: [], outputs: ["out"], fields: [{ key: "emoji", label: "Emoji filter", type: "text", placeholder: "Leave empty for any" }], emits: [{ name: "emoji", description: "Reacted emoji" }, { name: "user_id", description: "Who reacted" }, { name: "username", description: "Reactor's name" }, { name: "message_id", description: "Reacted message" }, { name: "channel_id", description: "Channel ID" }, { name: "timestamp", description: "When reacted" }] },
  { type: "trigger_on_command", label: "On Command", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: Terminal, inputs: [], outputs: ["out"], fields: [{ key: "command", label: "Command name", type: "text", placeholder: "!help" }, { key: "prefix", label: "Prefix", type: "text", placeholder: "!" }], emits: [{ name: "command", description: "Command name" }, { name: "args", description: "Arguments after command" }, { name: "content", description: "Full message" }, { name: "user_id", description: "Who ran command" }, { name: "username", description: "Runner's username" }, { name: "channel_id", description: "Channel ID" }, { name: "server_id", description: "Server ID" }, { name: "timestamp", description: "When ran" }] },
  { type: "trigger_on_keyword", label: "On Keyword", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: Search, inputs: [], outputs: ["out"], fields: [{ key: "keywords", label: "Keywords (comma sep.)", type: "text", placeholder: "hello, hi, hey" }], emits: [{ name: "content", description: "Message text" }, { name: "matched_keyword", description: "Which keyword matched" }, { name: "user_id", description: "Sender's user ID" }, { name: "username", description: "Sender's username" }, { name: "channel_id", description: "Channel ID" }, { name: "timestamp", description: "When sent" }] },
  { type: "trigger_on_schedule", label: "On Schedule", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: Clock, inputs: [], outputs: ["out"], fields: [{ key: "interval_min", label: "Interval (minutes)", type: "number", placeholder: "60" }], emits: [{ name: "timestamp", description: "Current time" }] },
  { type: "trigger_on_channel_create", label: "On Channel Create", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: PlusCircle, inputs: [], outputs: ["out"], fields: [], emits: [{ name: "channel_id", description: "New channel ID" }, { name: "channel_name", description: "New channel name" }, { name: "server_id", description: "Server ID" }, { name: "timestamp", description: "When created" }] },
  { type: "trigger_on_role_change", label: "On Role Change", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: Shield, inputs: [], outputs: ["out"], fields: [], emits: [{ name: "user_id", description: "Affected user ID" }, { name: "username", description: "Affected user" }, { name: "role_id", description: "Role ID" }, { name: "role_name", description: "Role name" }, { name: "server_id", description: "Server ID" }, { name: "timestamp", description: "When changed" }] },
  { type: "trigger_on_bot_start", label: "On Bot Start", category: "trigger", color: "bg-emerald-600", borderColor: "border-emerald-500", icon: Play, inputs: [], outputs: ["out"], fields: [], emits: [{ name: "timestamp", description: "Start time" }] },

  // ===== ACTIONS (messaging) =====
  { type: "action_send_message", label: "Send Message", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: Send, inputs: ["in"], outputs: ["out"], fields: [{ key: "channel_id", label: "Channel ID", type: "text", placeholder: "Channel ID" }, { key: "content", label: "Message", type: "textarea", placeholder: "Hello {{user}}!" }], emits: [] },
  { type: "action_send_dm", label: "Send DM", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: Mail, inputs: ["in"], outputs: ["out"], fields: [{ key: "content", label: "Message", type: "textarea", placeholder: "Hello!" }], emits: [] },
  { type: "action_reply", label: "Reply", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: Reply, inputs: ["in"], outputs: ["out"], fields: [{ key: "content", label: "Reply text", type: "textarea", placeholder: "Thanks!" }], emits: [] },
  { type: "action_add_reaction", label: "Add Reaction", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: SmilePlus, inputs: ["in"], outputs: ["out"], fields: [{ key: "emoji", label: "Emoji", type: "text", placeholder: "👍" }, { key: "message_id", label: "Message ID (empty = trigger msg)", type: "text", placeholder: "{{message_id}}" }], emits: [] },
  { type: "action_delete_message", label: "Delete Message", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: Trash2, inputs: ["in"], outputs: ["out"], fields: [{ key: "message_id", label: "Message ID (empty = trigger msg)", type: "text", placeholder: "{{message_id}}" }], emits: [] },
  { type: "action_pin_message", label: "Pin Message", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: Pin, inputs: ["in"], outputs: ["out"], fields: [{ key: "message_id", label: "Message ID (empty = trigger msg)", type: "text", placeholder: "{{message_id}}" }], emits: [] },
  { type: "action_send_embed", label: "Send Embed", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: FileText, inputs: ["in"], outputs: ["out"], fields: [{ key: "channel_id", label: "Channel ID (empty = current)", type: "text", placeholder: "{{channel_id}}" }, { key: "title", label: "Embed Title", type: "text", placeholder: "Title" }, { key: "description", label: "Embed Description", type: "textarea", placeholder: "Description" }, { key: "color", label: "Color (hex)", type: "text", placeholder: "#5865f2" }], emits: [] },
  { type: "action_edit_message", label: "Edit Message", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: Pencil, inputs: ["in"], outputs: ["out"], fields: [{ key: "message_id", label: "Message ID (empty = trigger msg)", type: "text", placeholder: "{{message_id}}" }, { key: "content", label: "New content", type: "textarea", placeholder: "Updated!" }], emits: [] },
  { type: "action_send_button", label: "Send Button", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: MousePointerClick, inputs: ["in"], outputs: ["out"], fields: [{ key: "channel_id", label: "Channel ID (empty = current)", type: "text", placeholder: "{{channel_id}}" }, { key: "label", label: "Button label", type: "text", placeholder: "Click me" }, { key: "content", label: "Message", type: "textarea", placeholder: "Click the button below" }], emits: [] },
  { type: "action_send_typing", label: "Send Typing", category: "action", color: "bg-blue-600", borderColor: "border-blue-500", icon: Loader2, inputs: ["in"], outputs: ["out"], fields: [{ key: "duration", label: "Duration (seconds)", type: "number", placeholder: "3" }], emits: [] },

  // ===== ACTIONS (server management) =====
  { type: "action_create_channel", label: "Create Channel", category: "action", color: "bg-indigo-600", borderColor: "border-indigo-500", icon: Hash, inputs: ["in"], outputs: ["out"], fields: [{ key: "name", label: "Channel name", type: "text", placeholder: "new-channel" }], emits: [{ name: "new_channel_id", description: "Created channel ID" }] },
  { type: "action_delete_channel", label: "Delete Channel", category: "action", color: "bg-indigo-600", borderColor: "border-indigo-500", icon: Trash2, inputs: ["in"], outputs: ["out"], fields: [{ key: "channel_id", label: "Channel ID", type: "text", placeholder: "Channel to delete" }], emits: [] },
  { type: "action_rename_channel", label: "Rename Channel", category: "action", color: "bg-indigo-600", borderColor: "border-indigo-500", icon: Pencil, inputs: ["in"], outputs: ["out"], fields: [{ key: "channel_id", label: "Channel ID", type: "text" }, { key: "name", label: "New name", type: "text", placeholder: "renamed-channel" }], emits: [] },
  { type: "action_assign_role", label: "Assign Role", category: "action", color: "bg-indigo-600", borderColor: "border-indigo-500", icon: ShieldPlus, inputs: ["in"], outputs: ["out"], fields: [{ key: "role_id", label: "Role ID", type: "text" }], emits: [] },
  { type: "action_remove_role", label: "Remove Role", category: "action", color: "bg-indigo-600", borderColor: "border-indigo-500", icon: ShieldMinus, inputs: ["in"], outputs: ["out"], fields: [{ key: "role_id", label: "Role ID", type: "text" }], emits: [] },
  { type: "action_kick_user", label: "Kick User", category: "action", color: "bg-orange-600", borderColor: "border-orange-500", icon: UserX, inputs: ["in"], outputs: ["out"], fields: [{ key: "reason", label: "Reason", type: "text", placeholder: "Rule violation" }], emits: [] },
  { type: "action_ban_user", label: "Ban User", category: "action", color: "bg-red-600", borderColor: "border-red-500", icon: Ban, inputs: ["in"], outputs: ["out"], fields: [{ key: "reason", label: "Reason", type: "text", placeholder: "Banned" }], emits: [] },
  { type: "action_mute_user", label: "Mute User", category: "action", color: "bg-orange-600", borderColor: "border-orange-500", icon: VolumeX, inputs: ["in"], outputs: ["out"], fields: [{ key: "duration_min", label: "Duration (min)", type: "number", placeholder: "10" }], emits: [] },
  { type: "action_set_nickname", label: "Set Nickname", category: "action", color: "bg-indigo-600", borderColor: "border-indigo-500", icon: Tag, inputs: ["in"], outputs: ["out"], fields: [{ key: "nickname", label: "Nickname", type: "text", placeholder: "Cool Name" }], emits: [] },

  // ===== LOGIC =====
  { type: "action_add_delay", label: "Delay", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: Timer, inputs: ["in"], outputs: ["out"], fields: [{ key: "seconds", label: "Seconds", type: "number", placeholder: "5" }], emits: [] },
  { type: "action_condition", label: "If / Else", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: GitBranch, inputs: ["in"], outputs: ["true", "false"], fields: [{ key: "variable", label: "Variable", type: "text", placeholder: "{{content}}" }, { key: "operator", label: "Operator", type: "select", options: [{ value: "==", label: "equals" }, { value: "!=", label: "not equals" }, { value: ">", label: "greater than" }, { value: "<", label: "less than" }, { value: "contains", label: "contains" }, { value: "starts_with", label: "starts with" }, { value: "ends_with", label: "ends with" }] }, { key: "value", label: "Value", type: "text", placeholder: "hi" }], emits: [] },
  { type: "action_random_choice", label: "Random Choice", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: Shuffle, inputs: ["in"], outputs: ["out"], fields: [{ key: "choices", label: "Choices (one per line)", type: "textarea", placeholder: "Hello!\nHi there!\nHey!" }], emits: [{ name: "random_result", description: "The chosen value" }] },
  { type: "action_loop", label: "Loop", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: Repeat, inputs: ["in"], outputs: ["body", "done"], fields: [{ key: "count", label: "Iterations", type: "number", placeholder: "3" }], emits: [{ name: "loop_index", description: "Current iteration (0-based)" }] },
  { type: "action_switch", label: "Switch", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: ListTree, inputs: ["in"], outputs: ["case_1", "case_2", "case_3", "default"], fields: [{ key: "variable", label: "Variable", type: "text", placeholder: "{{content}}" }, { key: "case_1", label: "Case 1 value", type: "text", placeholder: "hello" }, { key: "case_2", label: "Case 2 value", type: "text", placeholder: "bye" }, { key: "case_3", label: "Case 3 value", type: "text", placeholder: "help" }], emits: [{ name: "matched_case", description: "Which case matched" }] },
  { type: "action_foreach", label: "For Each", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: IterationCw, inputs: ["in"], outputs: ["body", "done"], fields: [{ key: "list_var", label: "List variable", type: "text", placeholder: "{{my_list}}" }, { key: "separator", label: "Separator", type: "text", placeholder: "," }], emits: [{ name: "item", description: "Current item" }, { name: "index", description: "Current index" }] },
  { type: "action_cooldown", label: "Cooldown", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: Hourglass, inputs: ["in"], outputs: ["allowed", "blocked"], fields: [{ key: "seconds", label: "Cooldown (seconds)", type: "number", placeholder: "30" }, { key: "per", label: "Per", type: "select", options: [{ value: "user", label: "Per User" }, { value: "channel", label: "Per Channel" }, { value: "global", label: "Global" }] }], emits: [{ name: "remaining", description: "Seconds remaining" }] },
  { type: "action_wait_for_message", label: "Wait for Message", category: "logic", color: "bg-amber-600", borderColor: "border-amber-500", icon: MessageCircle, inputs: ["in"], outputs: ["received", "timeout"], fields: [{ key: "timeout_sec", label: "Timeout (seconds)", type: "number", placeholder: "30" }, { key: "from_user", label: "From specific user", type: "select", options: [{ value: "same", label: "Same user" }, { value: "any", label: "Any user" }] }], emits: [{ name: "response_content", description: "Received message text" }, { name: "response_user", description: "Who responded" }] },

  // ===== DATA =====
  { type: "action_set_variable", label: "Set Variable", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Database, inputs: ["in"], outputs: ["out"], fields: [{ key: "var_name", label: "Variable name", type: "text", placeholder: "counter" }, { key: "var_value", label: "Value", type: "text", placeholder: "0" }], emits: [] },
  { type: "action_get_variable", label: "Get Variable", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Database, inputs: ["in"], outputs: ["out"], fields: [{ key: "var_name", label: "Variable name", type: "text", placeholder: "counter" }], emits: [{ name: "value", description: "The retrieved value" }] },
  { type: "action_log", label: "Log", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: ScrollText, inputs: ["in"], outputs: ["out"], fields: [{ key: "message", label: "Log message", type: "text", placeholder: "Debug: {{value}}" }], emits: [] },
  { type: "action_http_request", label: "HTTP Request", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Globe, inputs: ["in"], outputs: ["out"], fields: [{ key: "method", label: "Method", type: "select", options: [{ value: "GET", label: "GET" }, { value: "POST", label: "POST" }] }, { key: "url", label: "URL", type: "text", placeholder: "https://api.example.com/data" }], emits: [{ name: "response_body", description: "Response body" }, { name: "status_code", description: "HTTP status code" }] },
  { type: "action_json_parse", label: "Parse JSON", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Braces, inputs: ["in"], outputs: ["out"], fields: [{ key: "path", label: "JSON path", type: "text", placeholder: "data.items[0].name" }], emits: [{ name: "parsed_value", description: "Extracted value" }] },
  { type: "action_math", label: "Math", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Calculator, inputs: ["in"], outputs: ["out"], fields: [{ key: "expression", label: "Expression", type: "text", placeholder: "{{a}} + {{b}}" }], emits: [{ name: "math_result", description: "Computed result" }] },
  { type: "action_string_format", label: "Format String", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Type, inputs: ["in"], outputs: ["out"], fields: [{ key: "template", label: "Template", type: "text", placeholder: "Hello {{user}}, welcome!" }], emits: [{ name: "format_result", description: "Formatted string" }] },
  { type: "action_counter", label: "Counter", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Tally3, inputs: ["in"], outputs: ["out"], fields: [{ key: "var_name", label: "Counter name", type: "text", placeholder: "msg_count" }, { key: "operation", label: "Operation", type: "select", options: [{ value: "increment", label: "Increment" }, { value: "decrement", label: "Decrement" }, { value: "reset", label: "Reset" }] }], emits: [{ name: "counter_value", description: "New counter value" }] },
  { type: "action_regex_match", label: "Regex Match", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Regex, inputs: ["in"], outputs: ["match", "no_match"], fields: [{ key: "input", label: "Input", type: "text", placeholder: "{{content}}" }, { key: "pattern", label: "Regex pattern", type: "text", placeholder: "^hello\\s+(\\w+)" }, { key: "flags", label: "Flags", type: "text", placeholder: "i" }], emits: [{ name: "match", description: "Full match text" }, { name: "group_1", description: "Capture group 1" }, { name: "group_2", description: "Capture group 2" }] },
  { type: "action_store_list", label: "List Operations", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: List, inputs: ["in"], outputs: ["out"], fields: [{ key: "list_name", label: "List name", type: "text", placeholder: "my_list" }, { key: "operation", label: "Operation", type: "select", options: [{ value: "push", label: "Push item" }, { value: "pop", label: "Pop last" }, { value: "shift", label: "Shift first" }, { value: "clear", label: "Clear all" }, { value: "includes", label: "Check includes" }] }, { key: "item", label: "Item value", type: "text", placeholder: "{{user_id}}" }], emits: [{ name: "list_length", description: "List size" }, { name: "list_value", description: "Popped/shifted value" }, { name: "list_includes", description: "true/false for includes" }] },
  { type: "action_api_call", label: "API Call", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: Webhook, inputs: ["in"], outputs: ["success", "error"], fields: [{ key: "method", label: "Method", type: "select", options: [{ value: "GET", label: "GET" }, { value: "POST", label: "POST" }, { value: "PUT", label: "PUT" }, { value: "DELETE", label: "DELETE" }] }, { key: "url", label: "URL", type: "text", placeholder: "https://api.example.com" }, { key: "headers", label: "Headers (JSON)", type: "textarea", placeholder: '{"Authorization": "Bearer ..."}' }, { key: "body", label: "Body (JSON)", type: "textarea", placeholder: '{"key": "value"}' }], emits: [{ name: "response_body", description: "Response data" }, { name: "status_code", description: "HTTP status" }, { name: "response_headers", description: "Response headers" }] },
  { type: "action_embed_builder", label: "Embed Builder", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: LayoutDashboard, inputs: ["in"], outputs: ["out"], fields: [{ key: "title", label: "Title", type: "text", placeholder: "My Embed" }, { key: "description", label: "Description", type: "textarea", placeholder: "Embed content" }, { key: "color", label: "Color", type: "text", placeholder: "#5865f2" }, { key: "footer", label: "Footer", type: "text", placeholder: "Footer text" }, { key: "thumbnail_url", label: "Thumbnail URL", type: "text", placeholder: "https://..." }, { key: "field_1_name", label: "Field 1 Name", type: "text", placeholder: "Field name" }, { key: "field_1_value", label: "Field 1 Value", type: "text", placeholder: "Field value" }, { key: "field_2_name", label: "Field 2 Name", type: "text", placeholder: "Field name" }, { key: "field_2_value", label: "Field 2 Value", type: "text", placeholder: "Field value" }], emits: [] },
  { type: "action_poll", label: "Create Poll", category: "data", color: "bg-violet-600", borderColor: "border-violet-500", icon: BarChart3, inputs: ["in"], outputs: ["out"], fields: [{ key: "question", label: "Question", type: "text", placeholder: "What do you prefer?" }, { key: "options", label: "Options (one per line)", type: "textarea", placeholder: "Option A\nOption B\nOption C" }, { key: "duration_min", label: "Duration (minutes)", type: "number", placeholder: "5" }], emits: [{ name: "poll_id", description: "Created poll ID" }] },
];

export const NODE_DEF_MAP = Object.fromEntries(NODE_DEFS.map((d) => [d.type, d])) as Record<NodeType, NodeDef>;

export const NODE_CATEGORIES = [
  { key: "trigger", label: "Triggers", color: "text-emerald-400" },
  { key: "action", label: "Actions", color: "text-blue-400" },
  { key: "logic", label: "Logic", color: "text-amber-400" },
  { key: "data", label: "Data", color: "text-violet-400" },
] as const;
